# 일반 환경 변수 (ConfigMap)
apiVersion: v1
kind: ConfigMap
metadata:
  name: raffle-config
data:
  DB_WRITER_HOST: "data-pipeline-primary.ctysyyia4d93.eu-west-2.rds.amazonaws.com"
  DB_READER_HOST: "data-pipeline-replica.ctysyyia4d93.eu-west-2.rds.amazonaws.com"
  DB_NAME: "raffle"
  DB_USER: "admin"
---
# 민감한 보안 정보 (Secret)
apiVersion: v1
kind: Secret
metadata:
  name: raffle-secret
type: Opaque
data:
  # echo -n "비밀번호" | base64 명령어로 변환한 값을 넣어야 함
  DB_PASSWORD: "U3VwZXJTZWNyZXRQYXNzd29yZDEyMyE="