# V1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raffle-app-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: raffle
      version: v1
  template:
    metadata:
      labels:
        app: raffle
        version: v1
    spec:
      containers:
      - name: raffle-container
        image: "<ECR_URI_주소>:v1"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: raffle-config
        - secretRef:
            name: raffle-secret
