apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: my-raffle-app
  newName: 486053612615.dkr.ecr.eu-west-2.amazonaws.com/my-raffle-app
  newTag: cb9574a6583e1b60364d2a112be7cebf5c2d212e
