apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: my-raffle-app
  newName: 486053612615.dkr.ecr.eu-west-2.amazonaws.com/my-raffle-app
  newTag: f8bda7d4b8e5b363bbd54d6c7a7478473450dd3d
