apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: my-raffle-app
  newName: 486053612615.dkr.ecr.eu-west-2.amazonaws.com/my-raffle-app
  newTag: edde8066d7fa26e89dc7afce8b50a26c6d82bf6f
