apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raffle-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yooseongjin527/asac_de2_infra_1st
    targetRevision: main      # main 브랜치 감시
    path: k8s                 # k8s/ 폴더 전체 적용
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true       # Git에서 삭제된 리소스 → 클러스터에서도 삭제
      selfHeal: true    # kubectl로 직접 수정해도 Git으로 자동 복구
    syncOptions:
      - CreateNamespace=true
